#!/usr/bin/env bash
# install nginx on the server
# GET requesting a page using curl to return Hello World!
sudo apt update
sudo apt install nginx -y
echo "Hello World!" | sudo tee /var/www/html/fikayo.html

# Script to redirects traffic
echo "server {
	listen 80;
	listen [::]:80 default_server;

	root /var/www/html;
	index fikayo.html index.nginx-debian.html;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=AZg4uJkEa-4&feature=youtu.be&hd=1;
	}
}" | sudo tee /etc/nginx/sites-available/default

sudo service nginx start
