#!/usr/bin/env bash
# Script to configures an ubuntu server and config nginx
sudo apt-get update
sudo apt-get install nginx -y
echo "Hello World!" | sudo tee /var/www/html/index.html

#permently redirects traffic from to another url abd display the page

echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
text="\\\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=AZg4uJkEa-4&feature=youtu.be&hd=1;\t\n}\n\n\terror_page 404 /custom_404.html;\n\tlocation = custom_404.html {\n\t\tinternal;\n\t}\n"

sudo sed -i "53i $test" /etc/nginx/sites-enabled/default

# Configure Nginx so that its HTTP response contains a custom header
#       The name of the custom HTTP header must be X-Served-By
#       The value of the custom HTTP header must be the hostname of the server Nginx is running on

CONFIG="\\\n\tadd_header X-Served-By '$(hostname)';"
sudo sed -i "24i $CONFIG" /etc/nginx/sites-enabled/default

sudo service nginx start
