#!/usr/bin/env bash
# Configure  and install HAproxh on the ib-01 server
# HAproxy should traffic to web-01 and web-02 server
# Using roundrobin algorithm
# Manage HAproxy via init script
sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt update
sudo apt-get install -y haproxy=2.8.\*

# Edit config file
server_config=\
"
frondend http
	bind *:80
	default_backend web_backend
backend web_backend
	balance roundrobin
	server web-01 34.204.60.206:80 check
	server web-02 52:87:216:0:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Enable haproxy to be started bh init script
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo service haproxy restart
