#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
# Configure HAproxy so that it send traffic to web-01 and web-02
# Distribute requests using a roundrobin algorithm
# Make sure that HAproxy can be managed via an init script
sudo apt update -y
sudo apt-get install haproxy -y

# Edit confit file
server_config=\
"
frontend http
	bind *:80
	default_backend web_backend
backend web_backend
	balance roundrobin
	server 141946-web-01 34.204.60.206:80 check
	server 141946-web-02 52.87.216.0:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

sudo service haproxy restart
