#!/usr/bin/env bash
# Script that create a file
# Display To infinity and beyond indefinitely
# Display I hate the kill command when SIGTERM signal
# Displays Y U no love me?! when SIGINT is received
# Delete the file and terminates itself

echo $$ >> /var/run/myscript.pid
trap "echo 'I hate the kill command'; rm /var/run/myscript.pid; exit" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "rm /var/run/myscript.pid; exit" SIGQUIT

while true
do
	echo "To infinity and beyond"
	sleep 2
done
