#!/usr/bin/env bash
# Script that display To infinity and beyond indefinitely
# with 2 sleep in between each iteration
# I am invincible!!! when receiving a SIGTERM signal

trap "echo 'I am invincible!!!'" SIGTERM
while true
do
	echo "To infinity and beyond"
	sleep 2
done
