#!/usr/bin/env bash
# Script display numbers from 1 to 100
# Display FizzBuzz when number is multiple of 3 and 5
# Display Fizz when number is multiple of 3
# Display Buzz when number is multiple of 5
# otherwise display number
# in a list format

for num in {1..100}
do
	if ((num % 3 == 0 && num % 5 == 0))
	then
		echo "FizzBuzz"
	elif ((num % 3 == 0))
	then
		echo "Fizz"
	elif ((num % 5 == 0))
	then
		echo "Buzz"
	else
		echo "$num"
	fi
done
