#!/usr/bin/env bash
# Script that displays number from 1 to 20
# display 4 and then bad luck from China for 4th loop
# display 9 and then bad luck from Japan for 9th loop
# displag 17 and then bd luck from Italy for 17tth loop

number=1
while ((number <= 20))
do
	echo "$number"
	case $number in
		"4") echo "bad luck from China";;
		"9") echo "bad luck from Japan";;
		"17") echo "bad luck from Italy";;
 	esac
	((number++))
done
