#!/usr/bin/env bash
# Script that displays the time for 12 hours and 59 minutes
# displays hours from 0 - 12
# display minutes from 1 - 59

hour=0
while ((hour <= 12))
do
	echo "Hour: $hour"
	min=1
	while ((min <= 59))
	do
		echo "$min"
		((min++))
	done
	((hour++))
done
