#!/usr/bin/env bash
# Script that configures an ubuntu server
# localhost to 127.0.0.2
# facebook.com to 8.8.8.8
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2' ~/hosts.new
sed -i '2i8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
