#!/usr/bin/env bash
# Nginx running as main user
# listen to port 8080 only
pkill -f apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
chown nginx:nginx /etc/nginx/nginx.conf
sudo -u service nginx restart
