#!/usr/bin/env bash
# 7 line or less
pkill -f apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sed -i '1s/^/user nginx ;\n/' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restarti
